<MyRootLayout>:
    on_touch_down: self.ids.plt1.update_plot()
    orientation: 'vertical'
    TwoPlotsSharedXWidget:
        id: plt1
        size_hint: 1, .85
        pos_hint: {'top': .85, 'left':1}
        sourceX: ['2020-1','2020-12', '2020-30', '2020-52']
        sourceY: [[1,2,3,4], [1,3,6,10]]
        units : ['','']
        titles : ['individual','cumulative']
        ax_colors : ['r','b']
        formatter : '%d-%b'

<TwoPlotsSharedXWidget>:
